stages:
- build
- verify

variables:
  SONAR_ARGS: "\
  -Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} \
  -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_NAME}
  "

Shields4J:
  stage: build
  tags:
    - touchbit-shell
  script:
    - make build
  artifacts:
    when: always
    expire_in: 30 day
    paths:
      - "*/target/reports"

Sonar review:
  stage: verify
  dependencies:
    - Shields4J
  tags:
    - touchbit-shell
  except:
    - tags
  script:
    - >
      if [ "$CI_BUILD_REF_NAME" == "master" ]; then
        mvn compile sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS
      else
        mvn compile sonar:sonar -Dsonar.login=$SONAR_LOGIN $SONAR_ARGS -Dsonar.analysis.mode=preview
      fi
