/*
 * MIT License
 *
 * Copyright © 2019 TouchBIT.
 * Copyright © 2019 Oleg Shaburov.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package org.touchbit.shields4j.client.http.model;

/**
 * Free SVG icons for popular brands
 * Full list see here https://simpleicons.org/
 * <p>
 * Created by Oleg Shaburov on 15.04.2019
 * shaburov.o.a@gmail.com
 */
@SuppressWarnings("unused")
public enum Logo {

    GATSBY("Gatsby"),
    ADOBE_AFTER_EFFECTS("Adobe After Effects"),
    KAIOS("KaiOS"),
    TOR("Tor"),
    PODCASTS("Podcasts"),
    ADOBE_PREMIERE("Adobe Premiere"),
    JUSTGIVING("JustGiving"),
    GOG_COM("GOG.com"),
    SLACK("Slack"),
    MICROSOFT_ONENOTE("Microsoft OneNote"),
    PLAYER_ME("Player.me"),
    GRAPHQL("GraphQL"),
    SASS("Sass"),
    T_MOBILE("T-Mobile"),
    AURELIA("Aurelia"),
    ADOBE_INDESIGN("Adobe InDesign"),
    CODECOV("Codecov"),
    DISROOT("Disroot"),
    DRIBBBLE("Dribbble"),
    GITTER("Gitter"),
    PROCESSWIRE("ProcessWire"),
    RASPBERRY_PI("Raspberry Pi"),
    SONGKICK("Songkick"),
    FOURSQUARE("Foursquare"),
    INVISION("InVision"),
    COMMON_WORKFLOW_LANGUAGE("Common Workflow Language"),
    ANGULAR("Angular"),
    SLIDES("Slides"),
    CSS_WIZARDRY("CSS Wizardry"),
    INSTAGRAM("Instagram"),
    DEBIAN("Debian"),
    THE_MIGHTY("The Mighty"),
    MEETUP("Meetup"),
    STADIA("Stadia"),
    AUTOTASK("Autotask"),
    POCKET("Pocket"),
    PINTEREST("Pinterest"),
    SINA_WEIBO("Sina Weibo"),
    MASTERCARD("MasterCard"),
    TWILIO("Twilio"),
    GNU_SOCIAL("GNU social"),
    OPERA("Opera"),
    MACY_S("Macy’s"),
    NINTENDO_SWITCH("Nintendo Switch"),
    LIVESTREAM("Livestream"),
    REDBUBBLE("Redbubble"),
    APACHE("Apache"),
    MEGA("MEGA"),
    NETFLIX("Netflix"),
    TENCENT_QQ("Tencent QQ"),
    AIRBNB("Airbnb"),
    MICROSOFT_ACCESS("Microsoft Access"),
    CAKEPHP("CakePHP"),
    VERIZON("Verizon"),
    TOGGL("Toggl"),
    EBAY("eBay"),
    SERVER_FAULT("Server Fault"),
    AMD("AMD"),
    BITDEFENDER("Bitdefender"),
    TRAKT("Trakt"),
    GULP("Gulp"),
    ADOBE("Adobe"),
    DTUBE("DTube"),
    HUAWEI("Huawei"),
    KIRBY("Kirby"),
    MICROGENETICS("Microgenetics"),
    YANDEX("Yandex"),
    YOUTUBE("YouTube"),
    TINDER("Tinder"),
    ARCHIVE_OF_OUR_OWN("Archive of Our Own"),
    WEASYL("Weasyl"),
    NPM("NPM"),
    HUMBLE_BUNDLE("Humble Bundle"),
    QUANTOPIAN("Quantopian"),
    JABBER("Jabber"),
    JEKYLL("Jekyll"),
    RAILS("Rails"),
    TESLA("Tesla"),
    YELP("Yelp"),
    METEOR("Meteor"),
    ADOBE_CREATIVE_CLOUD("Adobe Creative Cloud"),
    FLIPBOARD("Flipboard"),
    TRAINERROAD("TrainerRoad"),
    UDEMY("Udemy"),
    KO_FI("Ko-fi"),
    ITCH_IO("Itch.io"),
    GNU("GNU"),
    CODEWARS("Codewars"),
    QUORA("Quora"),
    RUBY("Ruby"),
    SCALA("Scala"),
    LAST_FM("Last.fm"),
    PLURK("Plurk"),
    REDIS("Redis"),
    SAUCE_LABS("Sauce Labs"),
    MAKERBOT("MakerBot"),
    TED("TED"),
    ROLLUP_JS("rollup.js"),
    WOLFRAM("Wolfram"),
    WOLFRAM_LANGUAGE("Wolfram Language"),
    WOLFRAM_MATHEMATICA("Wolfram Mathematica"),
    REVERBNATION("ReverbNation"),
    JSDELIVR("jsDelivr"),
    SPARKFUN("SparkFun"),
    BUZZFEED("BuzzFeed"),
    GOOGLEP("Google+"),
    REASON("Reason"),
    JENKINS("Jenkins"),
    GMAIL("Gmail"),
    LARAVEL("Laravel"),
    PATREON("Patreon"),
    EVERPLACES("Everplaces"),
    ADDTHIS("AddThis"),
    GITLAB("GitLab"),
    RUBYGEMS("RubyGems"),
    ADOBE_ACROBAT_READER("Adobe Acrobat Reader"),
    SENTRY("Sentry"),
    EVENTBRITE("Eventbrite"),
    GIT("Git"),
    CODEIGNITER("CodeIgniter"),
    BOWER("Bower"),
    SOUNDCLOUD("SoundCloud"),
    HUBSPOT("HubSpot"),
    MICROSOFT_POWERPOINT("Microsoft PowerPoint"),
    PRODUCT_HUNT("Product Hunt"),
    HTML5("HTML5"),
    HIGHLY("Highly"),
    BLOGGER("Blogger"),
    SMASHING_MAGAZINE("Smashing Magazine"),
    FIGMA("Figma"),
    POSTMAN("Postman"),
    UBUNTU("Ubuntu"),
    AUTH0("Auth0"),
    PLURALSIGHT("Pluralsight"),
    REDDIT("Reddit"),
    KENTICO("Kentico"),
    SWIFT("Swift"),
    ZAPIER("Zapier"),
    Y_COMBINATOR("Y Combinator"),
    KLOUT("Klout"),
    MAGENTO("Magento"),
    BITLY("Bitly"),
    ORIGIN("Origin"),
    SPARKPOST("SparkPost"),
    SOGOU("Sogou"),
    STRAVA("Strava"),
    FACEIT("FACEIT"),
    ETSY("Etsy"),
    BUY_ME_A_COFFEE("Buy Me A Coffee"),
    DEVRANT("devRant"),
    DISCOVER("Discover"),
    JUPYTER("Jupyter"),
    BLENDER("Blender"),
    DRAUGIEM_LV("Draugiem.lv"),
    MONERO("Monero"),
    ODNOKLASSNIKI("Odnoklassniki"),
    MIX("Mix"),
    TWOO("Twoo"),
    STACK_OVERFLOW("Stack Overflow"),
    GRAFANA("Grafana"),
    FANDANGO("Fandango"),
    CLOUDFLARE("Cloudflare"),
    VIADEO("Viadeo"),
    OVERCAST("Overcast"),
    ADOBE_ILLUSTRATOR("Adobe Illustrator"),
    SLICKPIC("SlickPic"),
    GOODREADS("Goodreads"),
    MICRO_BLOG("Micro.blog"),
    TYPO3("TYPO3"),
    VLC_MEDIA_PLAYER("VLC media player"),
    BOOST("Boost"),
    WATTPAD("Wattpad"),
    D3_JS("D3.js"),
    CREATIVE_COMMONS("Creative Commons"),
    BITCOIN("Bitcoin"),
    SWARM("Swarm"),
    WIX("Wix"),
    MOZILLA_FIREFOX("Mozilla Firefox"),
    AMAZON("Amazon"),
    LEETCODE("LeetCode"),
    FUR_AFFINITY("Fur Affinity"),
    RSS("RSS"),
    MONOGRAM("Monogram"),
    FIDO_ALLIANCE("Fido Alliance"),
    PLEX("Plex"),
    GOOGLE_ALLO("Google Allo"),
    FNAC("Fnac"),
    GOLDENLINE("GoldenLine"),
    GOOGLE_KEEP("Google Keep"),
    UNTAPPD("Untappd"),
    GOOGLE_ANALYTICS("Google Analytics"),
    MONKEY_TIE("Monkey tie"),
    FIREBASE("Firebase"),
    LINUX("Linux"),
    DOCUSIGN("DocuSign"),
    IMDB("IMDb"),
    LAUNCHPAD("Launchpad"),
    SPRINT("Sprint"),
    LIBERAPAY("Liberapay"),
    SPREAKER("Spreaker"),
    QZONE("Qzone"),
    TAPAS("Tapas"),
    QWIKLABS("Qwiklabs"),
    MAILCHIMP("MailChimp"),
    JAVASCRIPT("JavaScript"),
    PINGDOM("Pingdom"),
    SNAPCHAT("Snapchat"),
    DAZN("DAZN"),
    KHAN_ACADEMY("Khan Academy"),
    ANDROID("Android"),
    ICQ("ICQ"),
    NVIDIA("NVIDIA"),
    KIK("Kik"),
    WECHAT("WeChat"),
    ENVATO("Envato"),
    ADOBE_TYPEKIT("Adobe Typekit"),
    ZERPLY("Zerply"),
    GROUPON("Groupon"),
    HOUZZ("Houzz"),
    TRULIA("Trulia"),
    QIITA("Qiita"),
    CIVICRM("CiviCRM"),
    SENSU("Sensu"),
    SHOPIFY("Shopify"),
    GUMTREE("Gumtree"),
    EMPIRE_KRED("Empire Kred"),
    NODEMON("Nodemon"),
    UPWORK("Upwork"),
    ADOBE_DREAMWEAVER("Adobe Dreamweaver"),
    WHEN_I_WORK("When I Work"),
    INSTACART("Instacart"),
    OPENSTREETMAP("OpenStreetMap"),
    EVENT_STORE("Event Store"),
    FREECODECAMP("freeCodeCamp"),
    XBOX("Xbox"),
    NODE_JS("Node.js"),
    MONGODB("MongoDB"),
    HULU("Hulu"),
    LINE("Line"),
    BASECAMP("Basecamp"),
    NGINX("NGINX"),
    FEEDLY("Feedly"),
    LETTERBOXD("Letterboxd"),
    EVERNOTE("Evernote"),
    TREEHOUSE("Treehouse"),
    GLASSDOOR("Glassdoor"),
    VIM("Vim"),
    SELLFY("Sellfy"),
    DEVIANTART("DeviantArt"),
    CASH_APP("Cash App"),
    HACKERRANK("HackerRank"),
    WHATSAPP("WhatsApp"),
    SPOTIFY("Spotify"),
    NEXTDOOR("Nextdoor"),
    KICKSTARTER("Kickstarter"),
    MICROSOFT_EXCEL("Microsoft Excel"),
    ESEA("ESEA"),
    PICARTO_TV("Picarto.TV"),
    GRAPHCOOL("Graphcool"),
    LINE_WEBTOON("LINE WEBTOON"),
    HOMIFY("homify"),
    SNAPCRAFT("Snapcraft"),
    SPEAKER_DECK("Speaker Deck"),
    KODING("Koding"),
    GAUGES("Gauges"),
    GOOGLE_HANGOUTS("Google Hangouts"),
    VUE_JS("Vue.js"),
    GEOCACHING("Geocaching"),
    CASTRO("Castro"),
    THE_MOVIE_DATABASE("The Movie Database"),
    MOO("Moo"),
    SKYLINER("Skyliner"),
    VINE("Vine"),
    NUXT_JS("Nuxt.js"),
    TRIPADVISOR("TripAdvisor"),
    STEEMIT("Steemit"),
    ADOBE_AUDITION("Adobe Audition"),
    ABOUT_ME("About.me"),
    BING("Bing"),
    GOOGLE_HANGOUTS_CHAT("Google Hangouts Chat"),
    MAGISK("Magisk"),
    NETLIFY("Netlify"),
    HERE("HERE"),
    SLASHDOT("Slashdot"),
    PINGUP("Pingup"),
    XING("Xing"),
    UMBRACO("Umbraco"),
    TRAVIS_CI("Travis CI"),
    GUMROAD("Gumroad"),
    FITBIT("Fitbit"),
    WEBSTORM("WebStorm"),
    RUNKEEPER("Runkeeper"),
    WP_ENGINE("WP Engine"),
    HACKHANDS("HackHands"),
    ZENDESK("Zendesk"),
    PROBOT("Probot"),
    DEEZER("Deezer"),
    PROTO_IO("Proto.io"),
    APPVEYOR("AppVeyor"),
    ADOBE_PHOTOSHOP("Adobe Photoshop"),
    GO("Go"),
    BANDCAMP("Bandcamp"),
    MINUTEMAILER("Minutemailer"),
    UDACITY("Udacity"),
    REACT("React"),
    JAVA("Java"),
    TENCENT_WEIBO("Tencent Weibo"),
    BEATS("Beats"),
    ELASTIC("Elastic"),
    ELASTIC_CLOUD("Elastic Cloud"),
    ELASTICSEARCH("Elasticsearch"),
    ELASTIC_STACK("Elastic Stack"),
    KIBANA("Kibana"),
    LOGSTASH("Logstash"),
    X_PACK("X-Pack"),
    PERISCOPE("Periscope"),
    AT_T("AT&T"),
    CO_OP("Co-op"),
    VIMEO("Vimeo"),
    XERO("Xero"),
    LIVEJOURNAL("LiveJournal"),
    SOURCEGRAPH("Sourcegraph"),
    F_SECURE("F-Secure"),
    HATENA_BOOKMARK("Hatena Bookmark"),
    BATH_ASU("Bath ASU"),
    EXPERTS_EXCHANGE("Experts Exchange"),
    SKYPE("Skype"),
    KAGGLE("Kaggle"),
    SITEPOINT("SitePoint"),
    NEO4J("Neo4j"),
    CEVO("CEVO"),
    SALESFORCE("Salesforce"),
    ARTSTATION("ArtStation"),
    COMPROPAGO("ComproPago"),
    GHOST("Ghost"),
    MATHWORKS("Mathworks"),
    YARN("Yarn"),
    TOPCODER("Topcoder"),
    WEBCOMPONENTS_ORG("webcomponents.org"),
    HOCKEYAPP("HockeyApp"),
    EVRY("EVRY"),
    WORDPRESS("WordPress"),
    GRAVATAR("Gravatar"),
    DELL("Dell"),
    KOTLIN("Kotlin"),
    VIRB("Virb"),
    TELEGRAM("Telegram"),
    SUPER_USER("Super User"),
    AVENTRIX("Aventrix"),
    CLOCKIFY("Clockify"),
    DEPENDABOT("Dependabot"),
    LINKEDIN("LinkedIn"),
    ARCH_LINUX("Arch Linux"),
    SEGA("Sega"),
    SAP("SAP"),
    XSPLIT("XSplit"),
    TEESPRING("Teespring"),
    A_500PX("500px"),
    WEBPACK("Webpack"),
    GOOGLE_PLAY("Google Play"),
    PANDORA("Pandora"),
    GARMIN("Garmin"),
    DOCKER("Docker"),
    ACM("ACM"),
    NEXTCLOUD("Nextcloud"),
    LINUX_FOUNDATION("Linux Foundation"),
    ICONJAR("IconJar"),
    HACKSTER("Hackster"),
    SPDX("SPDX"),
    TRELLO("Trello"),
    ADOBE_LIGHTROOM("Adobe Lightroom"),
    STRIPE("Stripe"),
    BRAND_AI("Brand.ai"),
    DRUPAL("Drupal"),
    CODEFORCES("Codeforces"),
    HEXO("Hexo"),
    TWITTER("Twitter"),
    KEYCDN("KeyCDN"),
    SCRIBD("Scribd"),
    VENMO("Venmo"),
    TYPESCRIPT("TypeScript"),
    VISUAL_STUDIO_CODE("Visual Studio Code"),
    STORIFY("Storify"),
    PLANGRID("PlanGrid"),
    CODECADEMY("Codecademy"),
    JQUERY("jQuery"),
    CSS3("CSS3"),
    MICROSOFT_OUTLOOK("Microsoft Outlook"),
    YAMMER("Yammer"),
    READ_THE_DOCS("Read the Docs"),
    NUGET("NuGet"),
    CPP("C++"),
    GOV_UK("GOV.UK"),
    INTEL("Intel"),
    CHASE("Chase"),
    AZURE_DEVOPS("Azure DevOps"),
    CASTORAMA("Castorama"),
    MICROSOFT_EDGE("Microsoft Edge"),
    WINDOWS("Windows"),
    MAIL_RU("Mail.Ru"),
    BUFFER("Buffer"),
    STACKSHARE("StackShare"),
    ELEMENTARY("elementary"),
    PAYPAL("PayPal"),
    MYSQL("MySQL"),
    CMAKE("CMake"),
    FLUTTER("Flutter"),
    CODERWALL("Coderwall"),
    RENREN("Renren"),
    IFIXIT("iFixit"),
    INTERNET_EXPLORER("Internet Explorer"),
    SIGNAL("Signal"),
    UIKIT("UIkit"),
    SHAZAM("Shazam"),
    DISQUS("Disqus"),
    KEYBASE("Keybase"),
    PIVOTAL_TRACKER("Pivotal Tracker"),
    POSTGRESQL("PostgreSQL"),
    JSFIDDLE("JSFiddle"),
    PYTHON("Python"),
    FURRY_NETWORK("Furry Network"),
    JOOMLA("Joomla"),
    MASTODON("Mastodon"),
    RIOT("Riot"),
    INTERCOM("Intercom"),
    STEEM("Steem"),
    MESSENGER("Messenger"),
    LET_S_ENCRYPT("Let’s Encrypt"),
    AMERICAN_EXPRESS("American Express"),
    DIGITALOCEAN("DigitalOcean"),
    DELICIOUS("Delicious"),
    OVH("OVH"),
    DBLP("dblp"),
    ZILLOW("Zillow"),
    ICLOUD("iCloud"),
    RISEUP("Riseup"),
    STUBHUB("StubHub"),
    R("R"),
    LANYRD("Lanyrd"),
    DAILYMOTION("Dailymotion"),
    CAMPAIGN_MONITOR("Campaign Monitor"),
    VK("VK"),
    STACK_EXCHANGE("Stack Exchange"),
    COURSERA("Coursera"),
    FLICKR("Flickr"),
    MIXCLOUD("Mixcloud"),
    MIXER("Mixer"),
    TOPTAL("Toptal"),
    XCODE("Xcode"),
    TUMBLR("Tumblr"),
    MICROSOFT_WORD("Microsoft Word"),
    ATLASSIAN("Atlassian"),
    BITBUCKET("Bitbucket"),
    HIPCHAT("HipChat"),
    DESIGNER_NEWS("Designer News"),
    DROPBOX("Dropbox"),
    JIRA("Jira"),
    PLAYSTATION("PlayStation"),
    PLAYSTATION_3("PlayStation 3"),
    PLAYSTATION_4("PlayStation 4"),
    SUBVERSION("Subversion"),
    MICROSOFT_ONEDRIVE("Microsoft OneDrive"),
    V8("V8"),
    IONIC("Ionic"),
    GOOGLE("Google"),
    GOOGLE_CHROME("Google Chrome"),
    GOOGLE_DRIVE("Google Drive"),
    GOOGLE_PODCASTS("Google Podcasts"),
    BEHANCE("Behance"),
    POWERSHELL("PowerShell"),
    FRAMER("Framer"),
    VAGRANT("Vagrant"),
    FACEBOOK("Facebook"),
    CLOJURE("Clojure"),
    CODIO("Codio"),
    HASHNODE("Hashnode"),
    DISCORD("Discord"),
    QUALCOMM("Qualcomm"),
    NATIVESCRIPT("NativeScript"),
    VISA("Visa"),
    SAMSUNG("Samsung"),
    SAMSUNG_PAY("Samsung Pay"),
    ROOTS("Roots"),
    PRISMIC("Prismic"),
    PHP("PHP"),
    LUA("Lua"),
    PINBOARD("Pinboard"),
    PROTONMAIL("ProtonMail"),
    BAIDU("Baidu"),
    SNYK("Snyk"),
    NUCLEO("Nucleo"),
    VIBER("Viber"),
    NINTENDO_GAMECUBE("Nintendo GameCube"),
    ESLINT("ESLint"),
    SPOTLIGHT("Spotlight"),
    MARKETO("Marketo"),
    ECLIPSE_IDE("Eclipse IDE"),
    HASKELL("Haskell"),
    FAVRO("Favro"),
    TWITCH("Twitch"),
    REDUX("Redux"),
    BOOTSTRAP("Bootstrap"),
    HEROKU("Heroku"),
    SPACEMACS("Spacemacs"),
    CIRCLE("Circle"),
    YAHOO("Yahoo!"),
    DOT_NET(".NET"),
    TAILS("Tails"),
    LGTM("LGTM"),
    GERRIT("Gerrit"),
    FEATHUB("FeatHub"),
    APPLE("Apple"),
    SCRUTINIZER_CI("Scrutinizer CI"),
    NINTENDO("Nintendo"),
    WII_U("Wii U"),
    WII("Wii"),
    AUTOMATIC("Automatic"),
    MICROSOFT("Microsoft"),
    GOOGLE_PAY("Google Pay"),
    ATOM("Atom"),
    SOURCEFORGE("SourceForge"),
    CONEKTA("Conekta"),
    CODESHIP("Codeship"),
    ETHEREUM("Ethereum"),
    ASANA("Asana"),
    STYLUS("Stylus"),
    KNOWN("Known"),
    CIRCLECI("CircleCI"),
    STATAMIC("Statamic"),
    AMAZON_AWS("Amazon AWS"),
    COFFEESCRIPT("CoffeeScript"),
    MONZO("Monzo"),
    CODACY("Codacy"),
    SUBLIME_TEXT("Sublime Text"),
    QUANTCAST("Quantcast"),
    MATTERNET("Matternet"),
    STYLESHARE("StyleShare"),
    PAGEKIT("Pagekit"),
    GRAV("Grav"),
    DRONE("Drone"),
    BIG_CARTEL("Big Cartel"),
    OCULUS("Oculus"),
    LIBRARYTHING("LibraryThing"),
    INSTAPAPER("Instapaper"),
    DJANGO("Django"),
    GITHUB("GitHub"),
    SIMPLE_ICONS("Simple Icons"),
    MEDIUM("Medium"),
    DEV_TO("dev.to"),
    MYSPACE("Myspace"),
    ZEIT("Zeit"),
    WIRE("Wire"),
    WIKIPEDIA("Wikipedia"),
    VSCO("VSCO"),
    UNSPLASH("Unsplash"),
    UBISOFT("Ubisoft"),
    UBER("Uber"),
    TIDAL("Tidal"),
    SYMFONY("Symfony"),
    STITCHER("Stitcher"),
    STEAM("Steam"),
    STATICMAN("Staticman"),
    SQUARESPACE("Squarespace"),
    SOCIETY6("Society6"),
    SAFARI("Safari"),
    RUST("Rust"),
    MOZILLA("Mozilla"),
    MEDIATEMPLE("MediaTemple"),
    MATRIX("Matrix"),
    MARKDOWN("Markdown"),
    JSON("JSON"),
    INKSCAPE("Inkscape"),
    HOOTSUITE("Hootsuite"),
    FLATTR("Flattr"),
    FLASK("Flask"),
    ELLO("Ello"),
    DISCOURSE("Discourse"),
    DIGG("Digg"),
    DIASPORA("Diaspora"),
    DENO("Deno"),
    CONDA_FORGE("Conda-Forge"),
    CODESANDBOX("CodeSandbox"),
    CODEPEN("CodePen"),
    CODE_CLIMATE("Code Climate"),
    APPLE_PAY("Apple Pay"),
    APPLE_MUSIC("Apple Music"),
    ANGELLIST("AngelList"),
    ;

    private String name;

    Logo(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return this.name;
    }
}
