name: Master

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'
    paths-ignore:
      - README.rst
      - LICENSE.rst
      - Makefile

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          java-package: jdk
          architecture: x64
      - name: Run tests
        run: mvn clean test
      - name: Run sonar
        env:
          SONAR_GH_CI_TOKEN: ${{ secrets.SONAR_GH_CI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn package sonar:sonar -DskipTests=true -Dsonar.login=${SONAR_GH_CI_TOKEN}
