name: Master

on:
  push:
    branches:
      - 'master'

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          java-package: jdk
          architecture: x64
      - name: Run tests
        run: mvn clean test
      - name: Run sonar
        run: mvn package sonar:sonar -DskipTests=true
        env:
          SONAR_GH_CI_TOKEN: ${{ secrets.SONAR_GH_CI_TOKEN }}
