name: Pull Request

on:
  pull_request:
    branches:
      - 'master'

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          java-package: jdk
          architecture: x64
      - name: Run tests
        run: mvn clean test
      - name: Run sonar
        env:
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          SONAR_GH_CI_TOKEN: ${{ secrets.SONAR_GH_CI_TOKEN }}
        run: |
          mvn package sonar:sonar -DskipTests=true \
          -Dsonar.login=${SONAR_GH_CI_TOKEN} \
          -Dsonar.pullrequest.key=${GITHUB_PR_NUMBER} \
          -Dsonar.pullrequest.branch=${GITHUB_HEAD_REF} \
          -Dsonar.pullrequest.base=${GITHUB_BASE_REF}
