name: Release

on:
  push:
    tags:
      - '*'

jobs:
  upload_sonatype:
    name: Sonatype
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: sonatype
          server-username: SONATYPE_LOGIN
          server-password: SONATYPE_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Set version (tag)
        run: mvn versions:set -DnewVersion=${GITHUB_REF##*/}
      - name: Publish to sonatype repository
        run: mvn deploy
        env:
          SONATYPE_LOGIN: ${{ secrets.SONATYPE_LOGIN }}
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
